version: '3.7'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: mydb
    environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: "human_resources"
        MYSQL_USER: "user"
        MYSQL_PASSWORD: "user123"
    ports:
      - "3306:3306"
    volumes:
      - ./src/test/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_ARBITRARY: 1
