spring:
  datasource:
    url: jdbc:mysql://localhost:3306/human_resources
    username: user
    password: user123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
